site_name: WebGear
site_url: https://haskell-webgear.github.io/
site_description: >-
  WebGear is a library to build composable, type-safe HTTP APIs in Haskell.
site_author: Raghu Kaippully
copyright: © 2025 Raghu Kaippully

repo_url: https://github.com/haskell-webgear/webgear

theme:
  name: material
  favicon: images/favicon.png
  icon:
    annotation: material/arrow-right-circle-outline
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  palette:
    primary: teal
    accent: indigo

plugins:
  - search
  - mike

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.1/css/fontawesome.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.1/js/fontawesome.min.js

extra:
  version:
    provider: mike
    default: stable

nav:
  - 'Home': index.md
  - 'Tutorial':
      - 'First Steps':
          - 'Introduction': tutorial/first-steps/introduction.md
          - 'Getting Started': tutorial/first-steps/getting-started.md
      - 'Request Handling':
          - 'Routing': tutorial/request-handling/routing.md
          - 'Handlers and Middlewares': tutorial/request-handling/handlers-and-middlewares.md
          - 'Request Traits': tutorial/request-handling/request-traits.md
          - 'Generating Responses': tutorial/request-handling/generating-responses.md
          - 'API Documentation': tutorial/request-handling/api-documentation.md
      - 'Advanced':
          - 'Arrows Primer': tutorial/advanced/arrows-primer.md
          - 'Traits': tutorial/advanced/traits.md
  - 'Packages': packages.md
